### ISSUE TITLE
Update to v1 GCF endpoints

### ISSUE THREAD

**Issue by drzax** [abcnews/poll-counters#1]
The Google Cloud Functions endpoints used in this project are scheduled for shutdown early 2020 so we need to [migrate these to the v1 endpoints](https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server).

**Comment by drzax** [comment]
Could you take a look at this over the quiet Christmas period @colingourlay? It looks like the same endpoints are used in https://github.com/abcnews/howlifehaschanged and https://github.com/abcnews/amazon-race-game.

**Comment by colingourlay** [comment]
This was resolved in 11c0ba5882b957d5dae5c24f9f245268403d4449 by updating to the latest `firebase-functions` version, which no longer communicates with the old metadata endpoints

**Comment by colingourlay** [comment]
Actually, it seems that `firebase-functions` still uses the `beta1` API internally. Someone's raised this with them, which we can track here: https://github.com/firebase/firebase-functions/issues/580

**Comment by colingourlay** [comment]
False alarm. I poked around the latest `firebase-functions` and they only touch that endpoint in their [outdated test fixtures](https://github.com/firebase/firebase-functions/search?q=computeMetadata%2Fv1beta1&unscoped_q=computeMetadata%2Fv1beta1). We should be fine, now that we're on `3.3.0`

**Comment by drzax** [comment]
Nice, thanks.
